### ISSUE TITLE
ValueControl generates elicitation with slot name different from slot key

### ISSUE THREAD

**Issue by Gabrielbdd** [alexa/ask-sdk-controls#41]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When asking the user to provide a required slot, the `ValueControl` adds an elicitation directive to the response builder:
```typescript
const slotElicitation = generateSlotElicitation(this.props.slotType);
builder.addElicitSlotDirective(slotElicitation.slotName, slotElicitation.intent);
```

## Expected Behavior

The elicitation directive slots should be named after their keys so that Alexa can understand the directive properly.

## Current Behavior

The slot to be elicited, is being generated with the key different than its name.
For example, when using a `ValueControl` with an custom slot named Test, the generated directive is the following:
```jsonc
{
  "type": "Dialog.ElicitSlot",
  "slotToElicit": "test",
  "updatedIntent": {
    "name": "test_ValueControlIntent",
    "slots": {
      "slotType": {
        "name": "test",
        "value": "",
        "confirmationStatus": "NONE"
      },
      // Remaining slots omitted for brevity
    },
    "confirmationStatus": "NONE"
  }
}
```
Because the slot key is named "slotType" and the slot name is named "test", it causes Alexa to calls the skill endpoint with an error request:
```json
{
  "type": "SessionEndedRequest",
  "requestId": "amzn1.echo-api.request.b7d35101-a174-4bac-b70f-cfbe7f40c5f1",
  "timestamp": "2020-12-30T14:45:28Z",
  "locale": "pt-BR",
  "reason": "ERROR",
  "error": {
    "type": "INVALID_RESPONSE",
    "message": "All slots must be non-null and assigned to a key with the same name"
  }
}
```

## Possible Solution

A possible solution, is to function `generateSlotElicitation` on `ValueControl.ts` the generate the slot with the same name and key:
```diff
function generateSlotElicitation(slotType: string): { intent: Intent; slotName: string } {
    const intent: Intent = {
        // TODO: refactor: use SingleValueControlIntent.intentName
        name: `${slotType}_ValueControlIntent`.replace('.', '_'),
        slots: {
-           slotType: { name: slotType, value: '', confirmationStatus: 'NONE' },
+           [slotType]: { name: slotType, value: '', confirmationStatus: 'NONE' },
            feedback: { name: 'feedback', value: '', confirmationStatus: 'NONE' },
            action: { name: 'action', value: '', confirmationStatus: 'NONE' },
            target: { name: 'target', value: '', confirmationStatus: 'NONE' },
            head: { name: 'head', value: '', confirmationStatus: 'NONE' },
            tail: { name: 'tail', value: '', confirmationStatus: 'NONE' },
            assign: { name: 'assign', value: '', confirmationStatus: 'NONE' },
        },
        confirmationStatus: 'NONE',
    };

    return {
        intent,
        slotName: slotType,
    };
}
```

## Your Environment

* ASK SDK Controls used: 0.4.0
* Operating System and version: Ubuntu 20.04.1 running on Windows WSL 2

## Node.js and NPM Info
* Node.js version used for development: 12.18.3 
* NPM version used for development: 6.14.8

I'm available to open a PR fixing this behavior 😄

**Comment by mikelid** [comment]
Great catch - thank you for finding this and props for identifying the correct fix 🥇 
PR: https://github.com/alexa/ask-sdk-controls/pull/42
