### ISSUE TITLE
Update API docs to add missing ComponentModeControlManager reference

### ISSUE THREAD

**Issue by sattpat** [alexa/ask-sdk-controls#54]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Your Environment

* ASK SDK Controls used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by Shreyas-vgr** [comment]
The doc updates have been merged into `develop` branch and will be pushed to prod on next release of `ask-sdk-controls`

**Comment by mikelid** [comment]
did the updates go in?

**Comment by mikelid** [comment]
roger. thank you.

**Comment by Shreyas-vgr** [comment]
Relesed the API reference on latest v0.6.1 release
https://ask-sdk-controls-typedoc.s3.amazonaws.com/classes/_controls_componentmodecontrolmanager_.componentmodecontrolmanager.html
