### ISSUE TITLE
My planner

### ISSUE THREAD

**Issue by jimmijammbf** [alexa/ask-sdk-controls#67]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Your Environment

* ASK SDK Controls used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by Shreyas-vgr** [comment]
Hi @jimmijammbf, Please re-open the issue with relevant information of any issues you're facing on using the ask-sdk-controls.

Closing due to insufficient information.
